In [1]:
import time
from dask.distributed import Client
import joblib

from CIFAR10_CNN import cifar10_cnn
from CIFAR10_CNN_Distributed import cifar10_cnn_distributed

C:\Users\megal\Anaconda3\lib\site-packages\dask\dataframe\utils.py:15: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


ImportError: cannot import name '_validate_shuffle_split_init' from 'sklearn.model_selection._split' (C:\Users\megal\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py)

In [9]:
client = Client(processes=False)             # create local cluster
# client = Client("scheduler-address:8786")  # or connect to remote cluster

model_10 = cifar10_cnn('cnn_model_10epochs.h5')
model_50 = cifar10_cnn('cnn_model_50epochs.h5')
model_100 = cifar10_cnn('cnn_model_100epochs.h5')
#model_dask = cifar10_cnn_dask()

# No dask no parallel
# epochs = 10
print('Starting non-distributed training...')
print('Starting model training (epochs=10)...')
start = time.time()
#model_10.run_test_harness(epochs=10, batch_size=64)
end = time.time()
print('Non-distributed completion time (epochs=10): ', end - start, 'seconds')

# epochs = 50
print('Starting model training (epochs=50)...')
start = time.time()
#model_50.run_test_harness(epochs=50, batch_size=64)
end = time.time()
print('Non-distributed completion time (epochs=50): ', end - start, 'seconds')

# epochs = 100
print('Starting model training (epochs=100)...')
start = time.time()
#model_100.run_test_harness(epochs=100, batch_size=64)
end = time.time()
print('Non-distributed completion time (epochs=100): ', end - start, 'seconds')
print()

# Dask parallel
print('Starting distributed model training...')
start = time.time()
with joblib.parallel_backend('dask'):
    model_10_dist = cifar10_cnn_distributed('cnn_model_10epochs_dist.h5')
    model_50_dist = cifar10_cnn_distributed('cnn_model_50epochs_dist.h5')
    model_100_dist = cifar10_cnn_distributed('cnn_model_100epochs_dist.h5')
    
    print('Starting distributed model training (epochs=10)...')
    start = time.time()
    model_10_dist.run_test_harness(epochs=10, batch_size=64)
    end = time.time()
    print('No dask completion time (epochs=10): ', end - start, 'seconds')
    
    print('Starting distributed model training (epochs=50)...')
    start = time.time()
    #model_50_dist.run_test_harness(epochs=50, batch_size=64)
    end = time.time()
    print('No dask completion time (epochs=50): ', end - start, 'seconds')
    
    print('Starting distributed model training (epochs=100)...')
    start = time.time()
    #model_100_dist.run_test_harness(epochs=100, batch_size=64)
    end = time.time()
    print('No dask completion time (epochs=100): ', end - start, 'seconds')
    
print('Distributed models done')

#No dask completion time (epochs=10):  2111.384060382843 seconds
#Starting model training (epochs=50)...
#No dask completion time (epochs=50):  8861.92734336853 seconds
#Starting model training (epochs=100)...
#Starting distributed model training (epochs=10)...
#No dask completion time (epochs=10):  1963.2309262752533 seconds

C:\Users\megal\Anaconda3\lib\site-packages\distributed\scheduler.py:1245: UserWarning: 
Could not launch service 'dashboard' on port 8787. Got the following message:

failed to validate _ServerOpts(...).prefix: expected a value of type str, got None of type NoneType
  self.start()


Starting non-distributed training...
Starting model training (epochs=10)...


KeyboardInterrupt: 

In [2]:
model_event_10 = cifar10_cnn('cnn_event_model_10epochs.h5', 'data_img')
model_event_50 = cifar10_cnn('cnn_event_model_50epochs.h5', 'data_img')
model_event_100 = cifar10_cnn('cnn_event_model_100epochs.h5', 'data_img')
#model_dask = cifar10_cnn_dask()

# No dask no parallel event images
print('Starting non-distributed event training...')
# epochs = 10
print('Starting event model training (epochs=10)...')
start = time.time()
model_event_10.run_test_harness(epochs=10, batch_size=64)
end = time.time()
print('Non-distributed event model completion time (epochs=10): ', end - start, 'seconds')
# epochs = 50
print('Starting event model training (epochs=50)...')
start = time.time()
model_event_50.run_test_harness(epochs=50, batch_size=64)
end = time.time()
print('Non-distributed event model completion time (epochs=50): ', end - start, 'seconds')
# epochs = 100
print('Starting event model training (epochs=100)...')
start = time.time()
model_event_50.run_test_harness(epochs=100, batch_size=64)
end = time.time()
print('Non-distributed event model completion time (epochs=100): ', end - start, 'seconds')

Starting non-distributed event training...
Starting event model training (epochs=10)...
Found 10000 files belonging to 10 classes.
Using 9000 files for training.
Found 10000 files belonging to 10 classes.
Using 1000 files for validation.
> 10.500
Non-distributed event model completion time (epochs=10):  28.79258418083191 seconds
Starting event model training (epochs=50)...
Found 10000 files belonging to 10 classes.
Using 9000 files for training.
Found 10000 files belonging to 10 classes.
Using 1000 files for validation.
> 10.000
Non-distributed event model completion time (epochs=50):  22468.89160966873 seconds
Starting event model training (epochs=100)...
Found 10000 files belonging to 10 classes.
Using 9000 files for training.
Found 10000 files belonging to 10 classes.
Using 1000 files for validation.
> 10.000
Non-distributed event model completion time (epochs=100):  22.712862968444824 seconds


In [3]:
import tensorflow_datasets as tfds
from keras.preprocessing import image
from tensorflow.data import AUTOTUNE
from tensorflow.keras.layers import Rescaling
from tensorflow.keras.preprocessing import image_dataset_from_directory
import numpy as np

train = image_dataset_from_directory(
    'data_img',
    label_mode='categorical',
    validation_split=0.1,
    subset="training",
    seed=0,
    color_mode="grayscale",
    batch_size=32,
    image_size=(32, 32)
)
test = image_dataset_from_directory(
    'data_img',
    label_mode='categorical',
    validation_split=0.1,
    subset="validation",
    seed=0,
    color_mode="grayscale",
    batch_size=32,
    image_size=(32, 32)
)

#normalization_layer = Rescaling(1./255)
#normalized_ds = train.map(lambda x, y: (normalization_layer(x), y))
#image_batch, labels_batch = next(iter(normalized_ds))
#first_image = image_batch[0]
# Notice the pixel values are now in `[0,1]`.
#print(np.min(first_image), np.max(first_image))

#train = train.cache().prefetch(buffer_size=AUTOTUNE)
#test = test.cache().prefetch(buffer_size=AUTOTUNE)

train_numpy = tfds.as_numpy(train)  # Convert `tf.data.Dataset` to Python generator

X_train = np.array(list(map(lambda x: x[0], train_numpy)))
y_train = np.array(list(map(lambda x: x[1], train_numpy)))

#print(X_train.shape)
#print(X_train[0].shape)

y_train = np.concatenate(y_train[:])
#y_train = y_train.reshape((len(y_train), 1))
print(y_train.shape)
print(y_train[0].shape)
print(y_train)

#X_train = np.concatenate(X_train[:])

#print(X_train.shape)
#print(X_train[0].shape)
#train_norm = X_train.astype('float32')
#for ex in ds_numpy:
    # `{'image': np.array(shape=(28, 28, 1)), 'labels': np.array(shape=())}`
#    print(ex[1])
#    break

Found 10000 files belonging to 10 classes.
Using 9000 files for training.
Found 10000 files belonging to 10 classes.
Using 1000 files for validation.
(9000, 10)
(10,)
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [2]:
from keras.datasets import cifar10
from tensorflow.keras.utils import to_categorical

(trainX, trainY), (testX, testY) = cifar10.load_data()
print(trainY.shape)
trainY = to_categorical(trainY)
print(trainY.shape)
print(trainY)

(50000, 1)
(50000, 10)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [2]:
from keras.models import load_model
import numpy as np

model_event_10 = cifar10_cnn('cnn_event_model_10epochs.h5', 'data_img')
model_event_10.run_test_harness(epochs=10, batch_size=64)

trainX, trainY, testX, testY = model_event_10.load_dataset_from_directory()

print(trainX)

train_norm = trainX.astype('float32')
train_norm = train_norm / 255.0
print(train_norm)

#result = model_event_10.model.predict(testX)
#classes_x=np.argmax(result,axis=1)
#print(classes_x)

Found 10000 files belonging to 10 classes.
Using 9000 files for training.
Found 10000 files belonging to 10 classes.
Using 1000 files for validation.
> 10.500
Found 10000 files belonging to 10 classes.
Using 9000 files for training.
Found 10000 files belonging to 10 classes.
Using 1000 files for validation.
[[[[ 45.]
   [144.]
   [ 58.]
   ...
   [ 49.]
   [205.]
   [ 75.]]

  [[ 48.]
   [ 59.]
   [112.]
   ...
   [ 50.]
   [ 17.]
   [ 43.]]

  [[ 93.]
   [139.]
   [  3.]
   ...
   [139.]
   [ 36.]
   [ 16.]]

  ...

  [[  0.]
   [  0.]
   [253.]
   ...
   [ 79.]
   [241.]
   [246.]]

  [[  0.]
   [  0.]
   [ 39.]
   ...
   [242.]
   [241.]
   [239.]]

  [[ 36.]
   [  0.]
   [  0.]
   ...
   [255.]
   [242.]
   [228.]]]


 [[[  0.]
   [  0.]
   [  0.]
   ...
   [182.]
   [ 14.]
   [  0.]]

  [[  0.]
   [248.]
   [  0.]
   ...
   [  0.]
   [ 14.]
   [  0.]]

  [[  1.]
   [  1.]
   [  0.]
   ...
   [  2.]
   [  0.]
   [ 14.]]

  ...

  [[208.]
   [235.]
   [254.]
   ...
   [250.]
   [239

In [2]:
import dask_ml
print(dask_ml.__version__)
import sklearn
sklearn.__version__

0.11.0


'1.0.2'